name: Sanity Build

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addingToCartTest

      - name: NASA SEWP Public Websites Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report
          path: cypress/reports/html
          
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Test Automation Report https://github.com/Yuonus/Cypress-E2ERepo/actions/runs/${{github.run_id}}'
          SLACK_TITLE: SEWP 6 QA Cypress Web Test ResulT
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
