name: Sanity Build

on:
  push:
    paths:
      - 'cypress/e2e/addingToCartTest.cy.js'

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addingToCartTest